service: fante-notifier

frameworkVersion: '3'

plugins:
  - serverless-offline
  - serverless-webpack

package:
  individually: true

provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: 20201221

  stage: production
  region: eu-central-1

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource: '${self:custom.dynamodb.highlightsTable}'

custom:
  dynamodb:
    highlightsTable: 'arn:aws:dynamodb:eu-central-1:${env:AWS_ACCOUNT}:table/highlights'
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk

functions:
  sendFanteEmail:
    handler: src/handlers/email.sendFanteEmail
    events:
      - schedule: cron(0 19 * * ? *)
    environment:
      HIGHLIGHTS_TABLE_ARN: ${self:custom.dynamodb.highlightsTable}
      MAIL_HOST: ${env:MAIL_HOST}
      MAIL_PORT: ${env:MAIL_PORT}
      MAIL_USER: ${env:MAIL_USER}
      MAIL_PASS: ${env:MAIL_PASS}
      MAIL_FROM: ${env:MAIL_FROM}
      MAIL_TO: ${env:MAIL_TO}

  importHighlights:
    handler: src/handlers/pocket.importHighlights
    events:
      - schedule: cron(0 2 * * ? *)
    environment:
      HIGHLIGHTS_TABLE_ARN: ${self:custom.dynamodb.highlightsTable}
      AWS_ACCOUNT: ${env:AWS_ACCOUNT}
      POCKET_CONSUMER_KEY: ${env:POCKET_CONSUMER_KEY}
      POCKET_ACCESS_TOKEN: ${env:POCKET_ACCESS_TOKEN}
