service: fante-notifier

frameworkVersion: '2'

plugins:
  - serverless-offline
  - serverless-webpack

package:
  individually: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

  stage: production
  region: eu-central-1

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource: '${self:custom.dynamodb.highlightsTable}'

custom:
  dynamodb:
    highlightsTable: 'arn:aws:dynamodb:eu-central-1:${env:AWS_ACCOUNT}:table/highlights'
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk

functions:
  importHighlights:
    handler: src/handlers/pocket.importHighlights
    events:
      - schedule: cron(0 2 * * ? *)
    environment:
      HIGHLIGHTS_TABLE_ARN: ${self:custom.dynamodb.highlightsTable}
      AWS_ACCOUNT: ${env:AWS_ACCOUNT}
      POCKET_CONSUMER_KEY: ${env:POCKET_CONSUMER_KEY}
      POCKET_ACCESS_TOKEN: ${env:POCKET_ACCESS_TOKEN}
